token available checks

diff --git a/.github/workflows/16-publish.yml b/.github/workflows/16-publish.yml
--- a/.github/workflows/16-publish.yml
+++ b/.github/workflows/16-publish.yml
@@ -22,6 +22,20 @@ jobs:
                 node-version: 22
                 registry-url: https://npm.pkg.github.com
                 scope: '@twinkalkumar'
+
+            - name: Show npm config
+              run: npm config list
+
+            - name: Check token exists
+              run: |
+                if [ -z "$NODE_AUTH_TOKEN" ]; then
+                echo "Token missing"
+                exit 1
+                else
+                echo "Token available"
+                fi
+              env:
+                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
             - name: Install dependencies
               run: npm install
@@ -29,4 +43,4 @@ jobs:
             - name: Publish package
               run: npm publish
               env:
-                Node_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
